### ISSUE TITLE
DRI01 - Nearest parking route - 4

### ISSUE THREAD

**Issue by corradopetrelli** [ByPassaRe/Pick-a-Park#1]
**As a Driver**,
**I want to** receive the route of the nearest parking spot 
**so that**  I will spend less time searching for a parking spot

**Tasks**:
- [x] Ask to activate GPS, if is not enabled @MargheritaRenieri 
- [x] Create an User Interface for adding the destination @MargheritaRenieri 
- [x] Check the added destination @0nism @MargheritaRenieri 
- [x] Create a GET API to search nearest parking spot @0nism 
- [x] Show the maps with the route from GPS position to selected parking spot @MargheritaRenieri 

**Condition of Satisfaction**:
- [x] If GPS is not enabled don't allow to continue with the navigation
- [x] After the inserting of the destination, the Driver will receive the route on the maps
