### ISSUE TITLE
MUN04 - Monitor parking spot - 2

### ISSUE THREAD

**Issue by 0nism** [ByPassaRe/Pick-a-Park#10]
**As a Municipality Employee**,
**I want to** monitor a parking spot
**so that** I can view its characteristics (in real-time)

**Tasks**:
- [x] Create GET Parking spot API @0nism 
- [x] Create User interface for viewing parking spots @0nism

**Condition of Satisfaction**:
- [x] Check that all parking spots are visualized
