### ISSUE TITLE
USER02 - Login - 1

### ISSUE THREAD

**Issue by corradopetrelli** [ByPassaRe/Pick-a-Park#12]
**As a User**,
**I want to** login to the platform
**so that** I can use its features

**Tasks**:
- [x] Create Login form with required fields @corradopetrelli 
- [x] Validate the required fields @corradopetrelli 
- [x] Provide a feedback of login @corradopetrelli 
- [x] Create Login API @corradopetrelli 

**Condition of Satisfaction**:
- [x] Login should provide a token to user
- [x] After successful login the user is redirected to his/her home page
- [x] After failure login there is an error feedback
- [x] Email field should follow the email pattern
