### ISSUE TITLE
PARCOM01 - Establish parking costs - 2

### ISSUE THREAD

**Issue by 0nism** [ByPassaRe/Pick-a-Park#14]
**As a Parking Company**,
**I want to** establish the costs of parking
**so that** I can set the best price possible

**Tasks**:
- [x] Create an User Interface for viewing all parking spots @0nism 
- [x] Create a form for adding parking spot price (mettere il prezzo non vuol dire attivare il parcheggio) @0nism 

**Condition of Satisfaction**:
- [x] Show error on negative price
