### ISSUE TITLE
USER03 - Logout - 2

### ISSUE THREAD

**Issue by corradopetrelli** [ByPassaRe/Pick-a-Park#16]
**As a User**,
**I want to** logout from the platform
**so that** I can exit the platform

**Tasks**:
- [x] Create Logout user interface @corradopetrelli 
- [x] Revoke token to user @corradopetrelli 
- [x] Create Logout API @corradopetrelli 

**Condition of Satisfaction**:
- [x] After successful logout the user is redirect to login page
- [x] After successful logout the user is not logged
