### ISSUE TITLE
MUN01 - Create parking spot - 2

### ISSUE THREAD

**Issue by corradopetrelli** [ByPassaRe/Pick-a-Park#2]
**As a Municipality Employee**,
**I want to** create a parking spot
**so that** it is available on the platform

**Tasks**:
- [x] Define Database Schema of Parking spot @0nism
- [x] Validate the required fields @0nism 
- [x] Create POST Parking Spot API @0nism 
- [x] Create User Interface for adding a parking spot @0nism 
- [x] Create a feedback after creation (successful or failed) @0nism 

**Condition of Satisfaction**:
- [x] Check that latitude and longitude are correct
- [x] Check that the parking spot is not usable after creation
- [x] After the creation should be a feedback (popup, intermediate page...)
