### ISSUE TITLE
MUN02 - Remove parking spot - 1

### ISSUE THREAD

**Issue by 0nism** [ByPassaRe/Pick-a-Park#24]
**As a Municipality Employee**,
**I want to** remove a parking spot
**so that** it is unavailable on the platform

**Tasks**:
- [x] Create interface to remove parking spot @0nism 
- [x] Create remove API for parking spot @0nism

**Condition of Satisfaction**:
- [x] Confirmation should be asked before removal
- [x] The parking spot should disappear from the list after removal
- [x] The parking spot should disappear from the system
