### ISSUE TITLE
MUN06 - Make parking spot available - 2

### ISSUE THREAD

**Issue by 0nism** [ByPassaRe/Pick-a-Park#25]
**As a Municipality**
**I want to** make a parking spot available
**so that** the drivers can park on it

**Tasks**:
- [x] Create interface to activate parking spot @0nism 
- [x] Create API functionality to activate parking spot @0nism 
- [x] Create API functionality to deactivate parking spot @0nism 

**Conditions of satisfaction**:
- [x] The parking spot should be clearly visible if activated or deactivated
- [x] Deactivated parking spots should not be assigned to drivers
