### ISSUE TITLE
USER05 - Authorization - 3

### ISSUE THREAD

**Issue by 0nism** [ByPassaRe/Pick-a-Park#26]
**As a User**,
**I want to** visualize only  the views i'm authorized to see
**so that** I have an easier user experience

**Tasks**:
- [x] User info page (after login) @corradopetrelli 
- [x] Make Logout redirect to home page @corradopetrelli 
- [x] Make pages visible based on user role @corradopetrelli 

**Condition of Satisfaction**:
- [x] Only pertinent pages should be visible
- [x] After logout i should be on home page
- [x] I should be on info page after login
