### ISSUE TITLE
MUNPOL01 - View parking issues - 2

### ISSUE THREAD

**Issue by 0nism** [ByPassaRe/Pick-a-Park#27]
**As a Municipality Police**,
**I want to** view a list of parking issues
**so that** I can fine the car's owners.

**Tasks**:
- [x] Create Parking issues list interface @MargheritaRenieri 
- [x] Create Parking issues API @MargheritaRenieri 

**Condition of Satisfaction**:
- [x] Interface should return issues after they are added
