### ISSUE TITLE
MUNPOL02 - Parking issue resolution - 1

### ISSUE THREAD

**Issue by 0nism** [ByPassaRe/Pick-a-Park#28]
**As a Municipality Police**,
**I want to** resolve a parking issue
**so that** I can inform the Municipality about misbehaviour

**Tasks**:
- [x] Add interface to resolve parking issue @MargheritaRenieri 
- [x] Create Parking issues resolve API @MargheritaRenieri 

**Condition of Satisfaction**:
- [x] Resolution should be confirmed
- [x] Resolved issues should appear on the list but immutable
