### ISSUE TITLE
MUN03 - Modify parking spot - 2

### ISSUE THREAD

**Issue by 0nism** [ByPassaRe/Pick-a-Park#29]
**As a Municipality Employee**,
**I want to** modify a parking spot
**so that** it gets updated on the platform

**Tasks**:
- [x] Create an interface to modify parking spot @0nism
- [x] Create API to modify the parking spot @0nism
- [x] Add confirm message before changes @0nism

**Condition of Satisfaction**:
- [x] Modifies should have a confirm
- [x] Fields should be filled with the already existing values
