### ISSUE TITLE
USER01 - Sign Up - 1

### ISSUE THREAD

**Issue by corradopetrelli** [ByPassaRe/Pick-a-Park#3]
**As a User**, 
**I want to** sign up to the platform
**so that** I can access to the services

**Tasks**:
- [x] Define Database Schema of User (with role) @corradopetrelli @0nism @MargheritaRenieri 
- [x] Create Sign Up form with required fields @corradopetrelli 
- [x] Create a feedback after registration (successful or failed) @corradopetrelli 
- [x] Validate the required fields @corradopetrelli 
- [x] Hash password @corradopetrelli 
- [x] Create Sign up API @corradopetrelli 

**Condition of Satisfaction**:
- [x] Check that email field follows the email pattern
- [x] Check that password has at least 8 characters
- [x] Check that password and confirm password are the same
- [x] After the registration should be a feedback (popup, intermediate page...)
