### ISSUE TITLE
USER06 - Bug report - 2

### ISSUE THREAD

**Issue by 0nism** [ByPassaRe/Pick-a-Park#31]
**As a User**,
**I want to** report a bug
**so that** I can send feedback

**Tasks**:
- [x] Create interface to report bugs @MargheritaRenieri 
- [x] Create interface to visualize bug reports by Parking Company @MargheritaRenieri 
- [x] Create Reporting Bug Report Create API @0nism
- [x] Create Reporting Bug Get API (with ParkCompany auth) @0nism 

**Condition of Satisfaction**:
- [x] Should display confirm of succesful send
- [x] Only parking company should see bug reports
