### ISSUE TITLE
DRI05 - Charge my account wallet - 3

### ISSUE THREAD

**Issue by corradopetrelli** [ByPassaRe/Pick-a-Park#36]
**As a Driver**,
**I want to** charge my account wallet (minimal),
**so that**  I can pay from the app

**Tasks**:
- [x] Create interface for charge account wallet (only add) @corradopetrelli 
- [x] Create API to charge account wallet (read and write) @corradopetrelli 

**Condition of Satisfaction**:
- [x] Feedback of successful charge
- [x] Visualize my account wallet
