### ISSUE TITLE
PARCOM03 - View parkings earning - 2

### ISSUE THREAD

**Issue by corradopetrelli** [ByPassaRe/Pick-a-Park#47]
**As a Parking Company**,
**I want to** view an earnings list
**so that** I can have an overview of all possible earning.

**Tasks**:
- [x] Create interface for visualize earnings @corradopetrelli 
- [x] Create API to get all transactions  @corradopetrelli
- [x] Connect API transaction to interface @corradopetrelli

**Condition of Satisfaction**:
- [x] I can visualize in a graphical way all earnings
- [x] I can visualize a single earning (grouped by a day)
- [x] I can zoom in/out the interface
