### ISSUE TITLE
DRI09 - Parking process - 5

### ISSUE THREAD

**Issue by 0nism** [ByPassaRe/Pick-a-Park#50]
**As a Driver**,
**I want to** start the parking process and pay on leave
**so that**  i can use the service

**Tasks**:
- [x] Should start paying calculation on parking @0nism 
- [x] Parking process starts if both gps and park are aligned @0nism 
- [x] Calculate the cost on leave and charge (can go in debt) @0nism 

**Condition of Satisfaction**:
- [x] Should not start parking process if GPS is not nearby the parking spot
- [x] I should be charged on leave
