### ISSUE TITLE
DRI08 - Navigation - 5

### ISSUE THREAD

**Issue by 0nism** [ByPassaRe/Pick-a-Park#51]
**As a Driver**,
**I want to** be updated on my travel status
**so that**  I can navigate to the destination

**Tasks**:
- [x] Move the position icon according to current GPS position @corradopetrelli 
- [x] Make Parking Spot not available to others @corradopetrelli  
- [x] Visualize at a proper zoom level @corradopetrelli 
- [x] Check if user has funds before assigning parking spot @corradopetrelli 
- [x] Create Prenotation API

(optional) Show instructions for turning @corradopetrelli  

**Condition of Satisfaction**:
- [x] Parking spot should be unavailable to others on calculated route
- [x] Zoom level should be user-friendly
